### DISCUSSION TITLE
Save and Load windows trees | A tool I wrote and I ported from Sway to Niri

### DISCUSSION THREAD

**Discussion by fabienjuif** [YaLTeR/niri#1933] [Show and tell]
Link: https://github.com/fabienjuif/swaytreesave

It allows me to switch my Niri windows/workspaces from working realm to personal one.
I use it like this:
- **work**: `swaytreesave --compositor niri --name work load`
- **personal**: `swaytreesave --compositor niri load`

If you do not want to start from fresh config file, you can save a current tree, then modify the saved tree manually, example: `swaytreesave --compositor niri save`, some trees examples at the end of this post.

It's less important if you are using window rule to tied a window to a workspace.
But I find this still useful to kill and restart a fresh "tree" (or "realm").

This is super early stage, I know there is some weird config etc.
This is mostly an excuse to write some Rust, but I thought it can be useful for other folks than me.

Feel free to fork it if you want.

### Example trees files

And here's are my 2 niri trees that are tied to commands above
**work**
```yaml
- name: chat
  type: workspace
  nodes:
  - nodes:
    - app_id: Slack
      desktop_entry: slack
      timeout: "1s"
    - app_id: discord
      desktop_entry: discord
      timeout: "1s"
    - app_id: signal
      desktop_entry: signal-desktop
      timeout: "1s"
    layout: splith
- name: browser
  type: workspace
  nodes:
  - nodes:
    - app_id: Firefox
      exec: /usr/lib/firefox/firefox -P Work
    - app_id: Firefox
      exec: /usr/lib/firefox/firefox -P default-default
    layout: splith
- name: code
  type: workspace
  nodes:
  - nodes:
    - app_id: code-oss
    layout: splith

```

**personal**
```yaml
- name: chat
  type: workspace
  nodes:
  - nodes:
    - app_id: discord
      desktop_entry: discord
      timeout: "1s"
    - app_id: signal
      desktop_entry: signal-desktop
      timeout: "1s"
    layout: splith
- name: browser
  type: workspace
  nodes:
  - nodes:
    - app_id: Firefox
      exec: /usr/lib/firefox/firefox -P default-default
    layout: splith
- name: code
  type: workspace
  nodes:
  - nodes:
    - app_id: code-oss
    layout: splith
```
