### DISCUSSION TITLE
Option to omit empty workspaces on ends from bar unless focused

### DISCUSSION THREAD

**Discussion by zetaPRIME** [YaLTeR/niri#875] [Ideas]
I'm not sure if the handling for this would be in the IPC or within the Waybar module, but being able to set things up such that empty workspaces on the ends of the set are only shown if focused would be a great look-and-feel tweak. Bonus points if said mode numbers `empty-workspace-above-first` as 0 until a window is opened there.

**Comment by YaLTeR** [comment]
I think it should be implemented in Waybar. It can check if the workspace has no windows.

**Comment by zetaPRIME** [comment]
I've implemented a hacky solution in my waybar css for now, but it's very css-dependent since gtk css doesn't support `display: none` at all:
```css
#workspaces button.empty:not(.active) { /* hide empty workspaces */
  margin-left: -10px;
  margin-right: -16px;
  padding: 0px;
  color: transparent;
  background-color: transparent;
  border: none;
}
```
