### ISSUE TITLE
Faulty Layer Shell Client Crashes Niri

### ISSUE THREAD

**Issue by Riolku** [YaLTeR/niri#1274]
I believe I am out of spec, but attaching one WlSurface to two different LayerShell surfaces causes a Niri panic (please do confirm if I am out of spec, I am not 100% sure).

The panic is [here](https://github.com/YaLTeR/niri/blob/62576796be91a5425abb6a1e8af35ebeca3fbcad/src/handlers/layer_shell.rs#L42).

Here's a simple MWE with wayrs:

```toml
[package]
name = "mwe"
version = "0.1.0"
edition = "2021"

[dependencies]
wayrs-client = "1.3.0"
wayrs-protocols = { version = "0.14.7", features = ["wlr-layer-shell-unstable-v1"] }
```

```rs
use wayrs_protocols::wlr_layer_shell_unstable_v1::zwlr_layer_shell_v1::Layer;
use wayrs_protocols::wlr_layer_shell_unstable_v1::ZwlrLayerShellV1;
use wayrs_client::protocol::WlCompositor;
use wayrs_client::Connection;

fn main() {
    let mut conn: Connection<()> = Connection::connect().expect("Connection failed");
    conn.blocking_roundtrip().expect("Roundtrip failed");

    let compositor: WlCompositor = conn.bind_singleton(1..=6).expect("Failed to bind compositor");
    let layer_shell: ZwlrLayerShellV1 = conn.bind_singleton(1).expect("Failed to bind layershell");

    let surface = compositor.create_surface(&mut conn);
    layer_shell.get_layer_surface(&mut conn, surface, None, Layer::Background, c"background".into());

    layer_shell.get_layer_surface(&mut conn, surface, None, Layer::Background, c"background".into());

    conn.blocking_roundtrip().expect("Roundtrip failed");
}
```

### System Information

* niri version: niri 25.02 (v25.02-64-g62576796)

* Distro: Arch

* GPU: AMD 6700 XT

* CPU: AMD Ryzen 5 5600X 6-Core
